STARTING TIMING RUN AT 2020-08-10 08:09:43 AM
running benchmark with seed 2
Traceback (most recent call last):
  File "official/resnet/imagenet_main.py", line 25, in <module>
    import numpy.random
ImportError: No module named 'numpy'
cat: /tmp/resnet_compliance_2.log: No such file or directory
ENDING TIMING RUN AT 2020-08-10 08:09:47 AM
RESULT,resnet,2,4,,2020-08-10 08:09:43 AM
